### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by SachaG** [Sanjo/meteor-meteor-files-helpers#1]
`MeteorFilesHelpers.getPackageVersion` works great locally, but when I try it in an app deployed on *.meteor.com I get the following error:

`TypeError: Arguments to path.resolve must be strings`

Does the package just not work in deployed/bundled apps? Or am I missing something?

**Comment by Sanjo** [comment]
It just doesn't work in deployed apps. I haven't looked into implementing the method for deployed apps. If there is a file like .meteor/version, it should be doable.

**Comment by SachaG** [comment]
Hmm, I was afraid of that. Well, if you find a way to do it please let me know!

**Comment by Sanjo** [comment]
I just had a look at the built app and there is no file that contains the versions.

I have an alternative idea. You could create a version-checker package that your other packages can weakly depend on. This package can expose an API: `VersionChecker.registerPackage(packageName, packageVersion)`. Then each package can register to the version checker. The package version would be encoded in this call. The version checker would check Atmosphere for newer versions and show something when the package is outdated.

**Comment by SachaG** [comment]
I did think about doing that, but I wanted to avoid having to specify the version twice if possible. Since I'm not sure if a `VersionChecker.registerPackage` API would work inside `package.js`.
