### ISSUE TITLE
Only for runtime.

### ISSUE THREAD

**Issue by trusktr** [Sanjo/meteor-meteor-files-helpers#4]
So I've realized, that if I make a package (f.e. `rocket:module`) that depends on these functions, it won't work if that package is using `MeteorFilesHelpers` during build stage (before deploying to Atmosphere for example) because then there's no way to use these helpers in a given application to be able to define build steps based on features found in an application.

In rocket:module, I was developing with local packages at first inside a test application, and that worked fine because rocket:module's build plugin would exist inside an app, and these helpers would work. But moving rocket:module to it's own folder outside of any application then publishing doesn't work because there's no reference application when the build plugin runs.

It seems like I will now have to move all this logic into the runtime environment and integrate with the application build steps somehow, but I'm not sure how yet.

Any ideas?

**Comment by Sanjo** [comment]
Is there a way how you can determine the app path from the build plugin? If yes, I can extend this package to allow to specify a custom app path as option.

**Comment by trusktr** [comment]
That's the problem, there's no way to do that in a build plugin unless the plugin is running in a locally installed package. If a build plugin could run for a package during app-build-time, that'd work out nicely.

**Comment by trusktr** [comment]
Closing since there's no need to know things like the app path during publish builds. Plus, the new `Plugin.registerCompiler` API runs during app builds, so all these helpers work great.
