### ISSUE TITLE
The Meteor tool is not always path.resolve(process.env.NODE_PATH, '../../..').

### ISSUE THREAD

**Issue by trusktr** [Sanjo/meteor-meteor-files-helpers#7]
For example, I cloned meteor/meteor, and it's actually `'../..'` from the node executable folder. There also isn't a `NODE_PATH` property in `process.env` in my case, but there are `process.execPath` and `process.argv[0]` which show the path to the node executable. For example:

```js
  argv:
   [ '/Users/josephpea/src/meteor+meteor/dev_bundle/bin/node',
     '/Users/josephpea/src/meteor+meteor/tools/main-transpile-wrapper.js' ],

...

  execPath: '/Users/josephpea/src/meteor+meteor/dev_bundle/bin/node',
```

**Comment by trusktr** [comment]
The solution is probably to just take the given argv[0] or execPath then do something like `findAppDir()` where it traverses up until finding what we want.

**Comment by Sanjo** [comment]
Jup, execPath probably. I will check it now.

**Comment by Sanjo** [comment]
Are you even on Windows? For other platforms it is `process.env.OLDPWD`.

**Comment by trusktr** [comment]
I'm on Mac OS X right now. Seems like MDG probably changed things up. I think the recursive strategy will be nice in case things ever change anyways. We basically know that `node` will be *somewhere* inside the folder that contains `meteor`, so we'll likely always find it recursively.

The reason I ended up here is because I was looking to see if there's a way to get the Meteor path, so I thought Id look at how getAppPath works, then I noticed there was a  getMeteorToolPath method, so I looked into that. :laughing: 

What I'm trying to do is `Npm.require` the `tools/isobuild/meteor-npm.js` file into rocket:module's build plugin. I figured I'd start first by getting the Meteor path, then constructing a path like `../../../../../path/to/meteor/tools/isobuild/meteor-npm.js` to pass into `Npm.require`.

**Comment by trusktr** [comment]
The default path that `Npm.require`starts at is located in the current app, so all the `../../../`s need to go to a folder common to both the app and Meteor (probably `/`).

**Comment by Sanjo** [comment]
I see. I will change the implementation now. I think you can just require an absolute path, can't you? Or path.relative to get a relative path.

**Comment by Sanjo** [comment]
Still need to test it on Mac and Windows now. Tested it on Ubuntu so far.

**Comment by trusktr** [comment]
> I think you can just require an absolute path, can't you? 

I wish. `Npm.require` simply appends whatever you pass it onto an internal path string, so `Npm.require('/absolute/path')` actually does `require('/path/to/app/somewhere-containing-node_modules/absolute/path')` behind the scenes.

**Comment by trusktr** [comment]
So the `../../../` would be required to make it work.

**Comment by trusktr** [comment]
Cool, your new solution is what I ended up doing too. :+1:

**Comment by trusktr** [comment]
Pushed to Atmosphere yet?

**Comment by Sanjo** [comment]
No. Give me 2 more minutes ;-)

**Comment by Sanjo** [comment]
It's now on Atmosphere as version 1.1.0_7.

**Comment by trusktr** [comment]
Awesome. I also made a new function:

```js
            Npm.requireFromMeteor = function(moduleName) {
                let meteorPath = getMeteorPath()
                let rootNpmPath = getMeteorNpmRequireRoot()
                let commonPath = getCommonAncestorPath(meteorPath, rootNpmPath)

                return Npm.require(
                    ''+
                    path.relative(rootNpmPath, commonPath) +
                    path.sep +
                    path.relative(commonPath, meteorPath) +
                    path.sep +
                    moduleName
                )
            }
```

I'll post it in `rocket:build-tools`. :smile:
